- name: Dummy Plugin
  hosts: localhost
  gather_facts: false
  vars:
    minio_server:
      - name: server1
        password: xyz
      - name: server2
        password: abc
    wanted: server1

  tasks:
    - name: Try updating apt
      apt:
        update_cache: true

    - name: Try installing package
      package:
        name: python3-jmespath
        state: present

    - name: Get all packages as facts
      package_facts:
        manager: auto

    - name: Debug
      debug:
        msg: '{{ minio_server
            | json_query("[? name==`" + wanted + "`].password | [0]") 
            }}'
